### ISSUE TITLE
Using positive on NumberInput throws a warning

### ISSUE THREAD

**Issue by adi2412** [Volicon/NestedLink#14]
Hi,

I tried using the positive prop with NumberInput. However, React throws the following warning-

"Warning: Unknown prop `positive` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

I believe this is due to the fact that the props are [directly passed](https://github.com/Volicon/NestedLink/blob/master/tags.jsx#L112) to the underlying input element in the render method of NumberInput.

**Comment by gaperton** [comment]
I see. You 're right. Will fix it soon.

**Comment by adi2412** [comment]
I've opened a pull request to fix this. You can merge it if you find it's alright

**Comment by gaperton** [comment]
Great. Thanks.
