### ISSUE TITLE
Question: can I calculate automatically?

### ISSUE THREAD

**Issue by mura-** [Volicon/NestedLink#18]
I want to set calculated result to state when update values.
can I do?

**Comment by gaperton** [comment]
Yes. By overriding the `component.setState()`.

For the nested objects inside of the state, it could be done with a [link.pipe](https://github.com/Volicon/NestedLink#-linkpipe-transform---next-prev---any---link) function.

```javascript
Link.state( this, 'obj' ).pipe( obj => {
    obj.calculated = obj.a + obj.b;
    return obj;
});
```

**Comment by mura-** [comment]
Thank you for your answer!
