### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by ckpinguin** [Volicon/NestedLink#20]
As in the docs, I use `import { Input } from 'valuelink/lib/tags'`
It's transpiling fine, but in the browser code I get:

`Uncaught SyntaxError: Unexpected token import
`
BTW in your README.md it's still ` import { Input } from 'valuelink/tags.jsx'`, but that file does not exist anymore in the NPM?

**Comment by gaperton** [comment]
> but in the browser code I get

Which kind of the browser? Is it IE?

> but that file does not exist anymore in the NPM?

I thought I removed it from the docs. Will keep it in NPM for the backward compatibility, though. It's the bug.

**Comment by gaperton** [comment]
> Uncaught SyntaxError: Unexpected token import

Ah, I think I understand what is happening. That's probably because of the fact that tags.tsx is being compiled with ES6 modules imports. So, it can work with webpack 2, but not with webpack 1.

Let me see what I can do, it's tricky.

**Comment by gaperton** [comment]
Okay, published the fix. Now, `valuelink/tags` is the CommonJS version of tags. Try this import line, it should work.

`import { Input } from 'valuelink/tags'`

Reopen if there are still any problems.

**Comment by ckpinguin** [comment]
I'm using create-react-app and a chrome browser, so webpack2 and browser compatibility should be no issue. 
I just updated to 1.4.3 (clean new install) and change the import line and it works now. Thanks a ton :-)
