### ISSUE TITLE
Documentation about type="radio"

### ISSUE THREAD

**Issue by Ridermansb** [Volicon/NestedLink#32]
Add documentation about radio types..

How can I do this..

```
<Input type="radio" name="radio" checked checkedLink={linked.at('image')} /> Banner
<Input type="radio" name="radio" checkedLink={linked.at('image')} /> Logo
```

I want a property image be a string with..

```
image: 'banner' or 'logo'
```

**Comment by gaperton** [comment]
linked.at( ‘image’ ).equals( ‘logo’ )

You don’t need checked attribute.

**Comment by gaperton** [comment]
https://github.com/Volicon/NestedLink/blob/master/docs/databinding.md#radio

**Comment by gaperton** [comment]
Or do it like this: https://github.com/Volicon/NestedLink/blob/master/docs/databinding.md#radio
