### ISSUE TITLE
valuelink cannot be used server side

### ISSUE THREAD

**Issue by jwalton** [Volicon/NestedLink#37]
Trying to `require` valuelink server-side results in an error complaining that `window` is not defined:

```
$ node
> require('valuelink')
ReferenceError: window is not defined
    at /Users/jwalton/benbria/loop/node_modules/valuelink/dist/index.js:1:982
    at n (/Users/jwalton/benbria/loop/node_modules/valuelink/dist/index.js:1:131)
```

It looks like this is some kind of artifact of using rollup to bundle things, because `window` is only referenced [here](https://github.com/Volicon/NestedLink/blob/35da7ca5033fbc23de86f0964aef37639f111268/example/todomvc/js/main.jsx#L31), which would never get executed server side in the first place.

**Comment by jwalton** [comment]
My co-worker @dule notes that removing [this line](https://github.com/Volicon/NestedLink/blob/35da7ca5033fbc23de86f0964aef37639f111268/rollup.config.js#L7) seems to fix this.

**Comment by gaperton** [comment]
Applied your fix, thanks.
