### ISSUE TITLE
LinkAll with React.useState hook

### ISSUE THREAD

**Issue by avkonst** [Volicon/NestedLink#40]
Thanks for the great library!

I typically link all state by using inheritance from LinkedComponent. It is a way based on class inheritance. It works. However, I have found that React Hooks from (16.8) simplify code a lot but they require components to be functions, not classes. I would like to use something similar to `this.linkAll()` but within functions where I could combine the links with `React.useState()`. I am trying to achieve something similar to the following. How should I do it properly?
```typescript
const MyComponent = (props: { data: { field1: string }}) => {
    const [state, setState] = React.useState(props.data);
    const links = AnalogyOfLinkAll(state, setState); // <----- How can I do this?
    return <input value={links.field1.value} onChange={(v) => links.field1.set(v)} />;
};
```

**Comment by gaperton** [comment]
Done. Not exactly like that, but I'd say it looks even better.

It seems that we don't need linkAll with hooks at all. Also, check the `examples/todomvc`. I updated it to use hooks. Much, much better than before.

https://medium.com/@gaperton/react-hooks-and-two-way-data-binding-dd4210f0ed94

**Comment by avkonst** [comment]
Alternatively, you can use valuelink from [react-use-state-x](https://github.com/avkonst/react-use-state-x), which I extracted today to opensource. Please, consider to reference it in your project as an alternative. I refer to yours one. Thanks.
