### ISSUE TITLE
export valuelink/tags.jsx as valuelink/tags

### ISSUE THREAD

**Issue by bjrmatos** [Volicon/NestedLink#6]
exporting a jsx file would require a compilation step for `node_modules` in other apps, other projects/react packages never export `jsx` file directly, they export the compiled version of `jsx` -> `js`, just like the export of `valuelink.js`

**Comment by gaperton** [comment]
Good, I will make the change.

**Comment by gaperton** [comment]
Fixed in 1.3.6
